- name: Ensure tomcat package is present
  apt:
    name: tomcat9
    state: present

- name: Ensure webapp is present
  copy: src={{ source_folder }}/hello-1.0.war dest={{ dest_folder }}/hello-1.0.war mode=0555
  notify:
    - restart tomcat
